### ISSUE TITLE
Create Supply Chain Front End API 

### ISSUE THREAD

**Issue by ALL306** [data61/Mirza#342]
String of text ok as format for company name, label, parties involved e.g. trucking company and farmer
For location will need a lat and long
Aim is that Cathy will be able to use front end API to make one call rather than multiple calls to supply chain and business registry. Ashley to create business registry front end API that supply chain front end API can call so Cathy can get data all back in a single call.

**Comment by a-stacey** [comment]
@sajidanower23 From the discussion from https://github.com/data61/Mirza/issues/340#issuecomment-456220499, we need to frame up the discussion for @cathylill.

Here is my first pass:
Do you have a preference for the data format for linked events in the supply chain? If you make a query for a supply chain would you prefer an array of events which were linked by id? something like:
```
{
  [
    {id: "uid", parent: "uid", child: "uid"},
    {id: "uid", parent: "uid", child: "uid"},
    {id: "uid", parent: "uid", child: "uid"}
  ]
}
```
or a structure that represents the hiracty natively in the structure:
```
{id: "uid", 
parent: {id: "uid", parent: ..., child: ...}, 
child: {id: "uid", parent: ..., child: ...}
}
```

I notice that the first solution is actually more flexible because it allows for arbitrarily complex structures (i.e. structures that have loops, structures that have forks and recombines (i.e. fruit is picked at one farm, sent to one of two plants for processing, the processed product from both plants is combined at a third plant and then turned back into a homogeneous product), structures that are partially complete so you could display part of a supply chain and then dynamically load more chunks for supply chains that were incredibly complexly detailed), but the second one maybe easier to process, because everything is somewhat just implicit. I think both meet the requirement of "reducing the number of incremental lookups required and there for latency and load time". Having realised all of this I think that the first option is preferable as it seems to meet all the requirements and have the most flexibility, but obviously only if it works with @cathylill constraints).

Let me know what you think @sajidanower23.

**Comment by a-stacey** [comment]
Yep sounds good, if you can come up with something better then lets go with that, that was mostly just framing up what I thought we discussed yesterday and a couple of realisations that I had when I actually went to write it down.
